let
    // Synthetic review only. 😀 Exact CRLF and trailing spaces are intentional.  
    Source = #"Sales Raw",
    Again = #"Sales Raw",
    Region = Environment,
    Step01 = Table.AddColumn(Source, "Synthetic analysis column 01", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step02 = Table.AddColumn(Step01, "Synthetic analysis column 02", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step03 = Table.AddColumn(Step02, "Synthetic analysis column 03", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step04 = Table.AddColumn(Step03, "Synthetic analysis column 04", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step05 = Table.AddColumn(Step04, "Synthetic analysis column 05", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step06 = Table.AddColumn(Step05, "Synthetic analysis column 06", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step07 = Table.AddColumn(Step06, "Synthetic analysis column 07", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step08 = Table.AddColumn(Step07, "Synthetic analysis column 08", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step09 = Table.AddColumn(Step08, "Synthetic analysis column 09", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step10 = Table.AddColumn(Step09, "Synthetic analysis column 10", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step11 = Table.AddColumn(Step10, "Synthetic analysis column 11", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step12 = Table.AddColumn(Step11, "Synthetic analysis column 12", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step13 = Table.AddColumn(Step12, "Synthetic analysis column 13", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step14 = Table.AddColumn(Step13, "Synthetic analysis column 14", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step15 = Table.AddColumn(Step14, "Synthetic analysis column 15", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step16 = Table.AddColumn(Step15, "Synthetic analysis column 16", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step17 = Table.AddColumn(Step16, "Synthetic analysis column 17", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step18 = Table.AddColumn(Step17, "Synthetic analysis column 18", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step19 = Table.AddColumn(Step18, "Synthetic analysis column 19", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step20 = Table.AddColumn(Step19, "Synthetic analysis column 20", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step21 = Table.AddColumn(Step20, "Synthetic analysis column 21", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step22 = Table.AddColumn(Step21, "Synthetic analysis column 22", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step23 = Table.AddColumn(Step22, "Synthetic analysis column 23", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step24 = Table.AddColumn(Step23, "Synthetic analysis column 24", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step25 = Table.AddColumn(Step24, "Synthetic analysis column 25", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step26 = Table.AddColumn(Step25, "Synthetic analysis column 26", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step27 = Table.AddColumn(Step26, "Synthetic analysis column 27", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step28 = Table.AddColumn(Step27, "Synthetic analysis column 28", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step29 = Table.AddColumn(Step28, "Synthetic analysis column 29", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step30 = Table.AddColumn(Step29, "Synthetic analysis column 30", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step31 = Table.AddColumn(Step30, "Synthetic analysis column 31", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Step32 = Table.AddColumn(Step31, "Synthetic analysis column 32", each "A long illustrative value for reading the complete transformation without a narrow inspector wrapping every few words", type text),
    Result = Table.Combine({Step32, Again})
in
    Result  
