'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{open}=require('./pq-redesign-independent-runtime-transport.cjs');
const root=path.resolve(__dirname,'..'),out=path.join(root,'docs/verification/pq-redesign/flow-0d964fc/chain-fallback');fs.mkdirSync(out,{recursive:true});
const R={candidate:'0d964fc97273cca8626e3cc4e9b39f73620b7e24',boundary:'T3 explicit unavailable / Do not retry; isolated Chrome long-chain only',checks:[],failures:[]};
(async()=>{const b=await open(),run=b.evaluate,save=(n,v)=>fs.writeFileSync(path.join(out,n+'.json'),JSON.stringify(v,null,2)+'\n'),button=t=>`[...document.querySelectorAll('button')].find(n=>n.textContent===${JSON.stringify(t)}&&n.getBoundingClientRect().width)`;
try{await b.send('Page.enable');await b.send('Network.enable');await b.send('Runtime.enable');await b.send('Emulation.setDeviceMetricsOverride',{width:1280,height:800,deviceScaleFactor:1,mobile:false});await b.send('Page.navigate',{url:'http://127.0.0.1:54093/'});await b.until('!!window.app&&app.state.showModelMenu','boot');await b.click(button('Import model (TMDL / BIM)'));await b.until('!!document.querySelector("input[type=file]")','fileinput');const doc=await b.send('DOM.getDocument'),input=await b.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'input[type=file]'});await b.send('DOM.setFileInputFiles',{nodeId:input.nodeId,files:[path.join(root,'tests/acceptance-fixtures/pq-redesign/flow-0d964fc/chain52.bim')]});await b.until('app.state.importReady','parsed');await b.click("[...document.querySelectorAll('button')].find(n=>/^(Add|Update) model/.test(n.textContent))");await b.click("[...document.querySelectorAll('nav button')].find(n=>n.textContent==='Power Query')");await b.until("app.powerQueryWorkspace.phase==='ready'",'ready');await b.click("[...document.querySelectorAll('.pqw-library-row')].find(n=>n.querySelector('strong').textContent==='FinalChain')");await b.click(button('Hide unrelated'));await b.click(button('Arrange'));await b.click(button('Fit'));await b.settle();
const data=await run(`(()=>{const w=app.powerQueryWorkspace,h=w.canvasHost.getBoundingClientRect(),cards=[...document.querySelectorAll('.pqc-node')].filter(n=>!n.hidden).map(n=>({id:n.dataset.nodeId,rect:n.getBoundingClientRect().toJSON()})),v=w.canvas.getViewport();return {innerWidth,innerHeight,registry:w.context.graph.nodes.length,visible:w.visible.size,root:w.flowRootId,direction:w.direction,depth:w.depth,view:v,canvas:h.toJSON(),cards,inViewport:cards.filter(n=>n.rect.right>h.left&&n.rect.left<h.right&&n.rect.bottom>h.top&&n.rect.top<h.bottom).length,computedFont:getComputedStyle(document.querySelector('.pqc-node-title')).fontSize,effectiveFont:parseFloat(getComputedStyle(document.querySelector('.pqc-node-title')).fontSize)*v.k,map:document.querySelector('.pqc-map-label').textContent}})()`);save('fit',data);assert.equal(data.registry,52);assert.equal(data.visible,52);assert.equal(data.root,'["partition","FinalChain","FinalChain"]');assert.equal(data.direction,'inputs');assert.equal(data.depth,null);fs.writeFileSync(path.join(out,'fit.png'),Buffer.from((await b.send('Page.captureScreenshot',{format:'png'})).data,'base64'));R.checks.push('52 exact resolved target ancestors available');R.usabilityObservation={zoom:data.view.k,effectiveFont:data.effectiveFont,cardsInViewport:data.inViewport,total:data.visible,userFitAccepted:false};
await b.click(button('Center selected'));const centered=await run('({view:app.powerQueryWorkspace.canvas.getViewport(),selected:document.querySelector(".pqc-selected").getBoundingClientRect().toJSON(),host:app.powerQueryWorkspace.canvasHost.getBoundingClientRect().toJSON()})');save('centered',centered);assert.ok(Math.abs((centered.selected.left+centered.selected.right)/2-(centered.host.left+centered.host.right)/2)<1);assert.ok(centered.view.k>=.85);R.checks.push('Center selected returns target to readable zoom');
}catch(err){R.failures.push(err.stack);process.exitCode=1}finally{save('receipt',R);save('network',b.events.filter(e=>/Network.requestWillBeSent|Runtime.exceptionThrown/.test(e.method)));await b.close();console.log(JSON.stringify(R,null,2))}})().catch(e=>{console.error(e);process.exitCode=1});
