'use strict';
// Scoped merged-runtime replay. Never imports a real source model or executes M/DAX.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const {open}=require('./pq-redesign-independent-runtime-transport.cjs');
const root=path.resolve(__dirname,'..'),base=path.join(__dirname,'acceptance-fixtures/pq-redesign'),out=path.join(root,'docs/verification/pq-redesign/runtime-e61726d'),mapping=require(path.join(out,'runtime-mapping.json'));
const origin=process.env.PQ_REPLAY_ORIGIN||'http://127.0.0.1:60907',runDir=path.join(out,process.env.PQ_REPLAY_RUN||'browser-01');fs.mkdirSync(runDir,{recursive:true});
function verify(){for(const a of mapping.assets){const buf=fs.readFileSync(path.join(out,'served',a.runtimePath));assert.equal(crypto.createHash('sha256').update(buf).digest('hex'),a.sha256);assert.deepEqual(buf,execFileSync('git',['show',mapping.candidate+':Models/tools/viewer/'+a.runtimePath],{cwd:root}));}assert.equal(mapping.assets.length,32);}
verify();const result={candidate:mapping.candidate,mapping:'exact 32 browser runtime assets; worktree feature files unchanged',boundary:'fresh isolated authorized Chrome CDP fallback; synthetic metadata; not native',startedAt:new Date().toISOString(),checks:[],failures:[]};
(async()=>{const b=await open(),run=b.evaluate,save=(n,v)=>fs.writeFileSync(path.join(runDir,n+'.json'),JSON.stringify(v,null,2)+'\n');
const shot=async n=>fs.writeFileSync(path.join(runDir,n+'.png'),Buffer.from((await b.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));
const button=t=>`[...document.querySelectorAll('button')].find(n=>n.textContent===${JSON.stringify(t)}&&n.getBoundingClientRect().width>0)`,nav=t=>`[...document.querySelectorAll('nav button')].find(n=>n.textContent===${JSON.stringify(t)})`;
const inspect=()=>run(`(()=>{const w=app.powerQueryWorkspace;return {phase:w.phase,category:w.category,query:w.query,selectedId:w.selectedId,inspectorOpen:w.inspectorOpen,banner:w.banner.textContent,message:w.message.textContent,code:[...document.querySelectorAll('.pqi-source-line')].map(n=>n.textContent).join(''),viewport:w.canvas.getViewport(),history:w.history,inspectorView:w.inspector.captureViewState(),visible:[...document.querySelectorAll('.pqc-node')].filter(n=>!n.hidden).map(n=>n.dataset.nodeId),library:[...w.list.querySelectorAll('button')].map(n=>n.textContent),options:[...w.filter.options].map(n=>n.textContent),sets:Object.fromEntries(Object.entries(w.sets||{}).map(([k,v])=>[k,[...v]])),graph:w.context?.graph}})()`);
async function check(name,fn){try{await fn();result.checks.push({name,status:'pass'});}catch(e){result.failures.push({name,error:e.stack});await shot('failure-'+result.failures.length);save('failure-'+result.failures.length,await inspect());}save('receipt',result);}
async function importFile(file){await b.click(button(await run('app.state.showModelMenu')?'Import model (TMDL / BIM)':'Open model'));await b.until('!!document.querySelector("input[type=file]")','import');const doc=await b.send('DOM.getDocument'),input=await b.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'input[type=file]'});await b.send('DOM.setFileInputFiles',{nodeId:input.nodeId,files:[file]});await b.until('app.state.importReady','parsed');await b.click("[...document.querySelectorAll('button')].find(n=>/^(Add|Update) model/.test(n.textContent))");await b.until('!app.state.showImport','committed');await b.settle();}
async function pq(){await b.click(nav('Power Query'));await b.until("app.powerQueryWorkspace.phase==='ready'",'PQ ready');await b.settle();}
async function select(t){await b.click(`[...document.querySelectorAll('.pqw-library-row')].find(n=>n.textContent.startsWith(${JSON.stringify(t+' ·')}))`);await b.settle();}
async function filter(c,q){await run(`(()=>{const w=app.powerQueryWorkspace;w.filter.value=${JSON.stringify(c)};w.filter.dispatchEvent(new Event('change',{bubbles:true}));w.search.value=${JSON.stringify(q)};w.search.dispatchEvent(new Event('input',{bubbles:true}));})()`);await b.settle();}
const tableState=()=>run('({view:app.canvas.view,pos:app.canvas.pos,selected:app.state.selected,marked:[...app.canvas.marked]})');
try{
await b.send('Page.enable');await b.send('Network.enable');await b.send('Runtime.enable');await b.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await b.send('Page.navigate',{url:origin+'/'});await b.until("!!window.app && app.state.modelName==='Choose a model' && app.state.showModelMenu",'registered empty boot');result.browser=await b.send('Browser.getVersion');
await importFile(path.join(base,'main-integration-e61726d/model.bim'));
await check('Tables → PQ → Tables retains viewport layout selection marks; PQ Escape is isolated',async()=>{
 await b.click(nav('Tables'));await run("app.canvas.selectTable('SyntheticSales',{keepView:true});app.canvas.setMarked(['SyntheticSales']);app.canvas.view={x:137,y:93,k:.9};app.canvas.updateTransform()");await b.settle();await b.settle();const before=await tableState();await pq();await select('OccurrenceProbe');await run("document.querySelector('.pqi-code-scroll').focus()");await b.key('Escape');await b.settle();const escaped=await inspect();assert.equal(escaped.inspectorOpen,false);assert.equal(await run('document.activeElement.dataset.nodeId'),JSON.stringify(['expression','','OccurrenceProbe']));await b.click(nav('Tables'));await b.settle();await b.settle();const after=await tableState();save('tables-route',{before,escaped,after});assert.deepEqual(after,before);await shot('tables-retained');
});
await check('Filter hidden selection, exact-reference reveal, Back and reset retain context',async()=>{
 await pq();await select('OccurrenceProbe');let entry=await inspect();assert.equal(entry.graph.nodes.length,5);assert.equal(entry.graph.edges.length,3);assert.equal(entry.sets.connected.length,4);assert.equal(entry.sets.disconnected.length,1);
 await filter('disconnected','Occurrence');await run('app.powerQueryWorkspace.canvas.setViewport({x:123,y:87,k:1.3});document.querySelector(".pqi-reference").focus()');await b.settle();const before=await run('app.powerQueryWorkspace.captureNavigation()'),hidden=await inspect();assert.equal(hidden.visible.length,1);assert.equal(hidden.library.length,0);assert.ok(hidden.banner.includes('hidden by filter'));await b.key('Enter');await b.settle();const linked=await inspect();assert.equal(linked.selectedId,JSON.stringify(['expression','','Sales Raw']));assert.equal(linked.category,'all');assert.equal(linked.query,'');assert.ok(linked.message.includes('Filters cleared'));await b.click(button('Back'));await b.settle();await b.settle();const back=await run('app.powerQueryWorkspace.captureNavigation()');save('filter-history',{entry,hidden,before,linked,back});assert.deepEqual(back,before);await run(button('Reset filters')+'.focus()');const prior=await inspect();await b.key('Enter');await b.settle();await b.settle();const reset=await inspect();save('filter-reset',{prior,reset});for(const k of ['selectedId','code','viewport','inspectorView','history'])assert.deepEqual(reset[k],prior[k]);assert.equal(reset.category,'all');assert.equal(reset.query,'');await shot('pq-exact');
});
await check('Exact CRLF and five quoted/repeated references survive merged parser; exact clipboard',async()=>{
 await filter('all','');await select('OccurrenceProbe');const exact=fs.readFileSync(path.join(base,'exact-source.m'),'utf8'),expected=JSON.parse(fs.readFileSync(path.join(base,'oracle.json'))).cases['a4-occurrences'].occurrences[JSON.stringify(['expression','','OccurrenceProbe'])];assert.equal((await inspect()).code,exact);assert.deepEqual(await run("[...document.querySelectorAll('.pqi-reference')].map(n=>n.textContent)"),expected.map(r=>r.text));const rows=[];for(let i=0;i<expected.length;i++){await run(`document.querySelectorAll('.pqi-reference')[${i}].focus();app.powerQueryWorkspace.canvas.setViewport({x:123,y:87,k:1.3})`);const before=await run('app.powerQueryWorkspace.captureNavigation()');await b.key('Enter');await b.settle();assert.equal((await inspect()).selectedId,expected[i].id);await b.click(button('Back'));await b.settle();await b.settle();const after=await run('app.powerQueryWorkspace.captureNavigation()');rows.push({i,before,after});assert.deepEqual(after,before);}await b.send('Browser.grantPermissions',{origin,permissions:['clipboardReadWrite','clipboardSanitizedWrite']});await b.send('Page.bringToFront');await b.click(button('Copy M'));await b.until("document.querySelector('.pqi-copy-status').textContent==='Copied exact M'",'copy');assert.equal(await run('navigator.clipboard.readText()'),exact);save('exact-crlf',{rows,clipboardExact:true,utf16Length:exact.length});
});
async function measures(label){await b.click(nav('Measures'));await b.until('!!document.querySelector(".mv-library-row")','Measures library');await b.click(`[...document.querySelectorAll('.mv-library-row')].find(n=>n.querySelector('.mv-row-name')?.textContent==='Formatted Probe')`);await b.settle();assert.equal(await run('app.state.selMeasure'),'Formatted Probe');assert.equal(await run('typeof DaxFormat.format'),'function');const values={};for(const style of ['original','long','short']){await run(`(()=>{const s=document.querySelector('select[aria-label="DAX layout"]');s.value=${JSON.stringify(style)};s.dispatchEvent(new Event('change',{bubbles:true}))})()`);await b.settle();values[style]=await run("[...document.querySelectorAll('.mv-dax-body')].map(n=>n.innerText)");assert.ok(values[style].join('').includes('DIVIDE'));}assert.notDeepEqual(values.long,values.original);save(label,values);await shot(label);return values;}
await check('Main Measures entry and original/long/short DAX UI formatting',async()=>{await measures('measures-online');await b.click(nav('Tables'));await b.settle();assert.equal(await run('app.state.viewMode'),'graph');await pq();assert.equal((await inspect()).code,fs.readFileSync(path.join(base,'exact-source.m'),'utf8'));});
await check('Default snapshot privacy and offline Measures formatter/PQ unavailable',async()=>{
 const download=path.join(runDir,'download');fs.mkdirSync(download,{recursive:true});await b.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:download,eventsEnabled:true});await b.click(button('Save snapshot'));await b.until('!app.state.snapshotSaving','snapshot');assert.equal(await run('app.state.snapshotError'),'');const start=Date.now();let files;do{files=fs.readdirSync(download).filter(x=>x.endsWith('.html'));if(files.length)break;await new Promise(r=>setTimeout(r,50));}while(Date.now()-start<15000);assert.equal(files.length,1);const file=path.join(download,files[0]),html=fs.readFileSync(file,'utf8'),payload=JSON.parse(html.match(/<script[^>]*id="smv-snapshot-data"[^>]*>([\s\S]*?)<\/script>/)[1]);for(const token of ['powerQuery','PQ_REDESIGN_','pq-redesign.invalid'])assert.ok(!JSON.stringify(payload).includes(token));assert.ok(!html.includes('PQ_REDESIGN_'));assert.ok(JSON.stringify(payload).includes('DIVIDE'));assert.ok(html.includes('DaxFormat'));const requests=b.events.filter(e=>e.method==='Network.requestWillBeSent').map(e=>e.params.request.url);assert.equal(requests.filter(u=>u.includes('.invalid')||u.includes('model-data.json')).length,0);save('snapshot-export',{payload,bytes:Buffer.byteLength(html),requests});await b.send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await b.send('Page.navigate',{url:'file://'+file});await b.until('!!window.app && app.snapshotMode','offline snapshot');await measures('measures-offline');await b.click(nav('Power Query'));await b.settle();const offline=await inspect();assert.equal(offline.visible.length,0);assert.equal(offline.code,'');assert.ok(offline.message.includes('unavailable'));save('snapshot-offline',offline);await shot('snapshot-offline');
});
verify();result.assetsReverified=32;
}finally{result.endedAt=new Date().toISOString();save('receipt',result);save('network',b.events.filter(e=>/Network.requestWillBeSent|Network.loadingFailed|Runtime.exceptionThrown/.test(e.method)));await b.close();console.log(JSON.stringify(result,null,2));if(result.failures.length)process.exitCode=1;}
})().catch(e=>{console.error(e);process.exitCode=1});
