'use strict';
// Explicitly authorized narrow fallback: actual fresh T3-downloaded snapshot only.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {open}=require('./pq-redesign-independent-runtime-transport.cjs');
const base=path.resolve(__dirname,'../docs/verification/pq-redesign/round8-12ae2e9'),out=path.join(base,'offline');fs.mkdirSync(out);
const receipt={candidate:'12ae2e9149590fde8a3292d22ce1d27c11a2aae4',boundary:'Explicit capability fallback while T3 available; isolated headless Chrome, network offline; not installed/native',checks:[],failures:[]};
(async()=>{const b=await open(),save=(n,v)=>fs.writeFileSync(path.join(out,n+'.json'),JSON.stringify(v,null,2)+'\n'),run=b.evaluate;
const button=t=>`[...document.querySelectorAll('button')].find(n=>n.textContent===${JSON.stringify(t)}&&n.getBoundingClientRect().width>0)`;
try{await b.send('Page.enable');await b.send('Network.enable');await b.send('Runtime.enable');await b.send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await b.send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
 const file=path.join(base,'privacy/downloaded.html'),data=fs.readFileSync(file);receipt.snapshotSHA256=crypto.createHash('sha256').update(data).digest('hex');await b.send('Page.navigate',{url:'file://'+file});await b.until('!!window.app&&app.snapshotMode','offline boot');
 assert.equal(await run('typeof WorkspaceUI.createCardChrome'),'function');assert.equal(await run("Snapshots.files.includes('js/workspace-ui.js')"),true);
 await b.click("[...document.querySelectorAll('nav button')].find(n=>n.textContent==='Measures')");await b.until('!!document.querySelector(".mv-library-row")','measures');await b.click("[...document.querySelectorAll('.mv-library-row')].find(n=>n.querySelector('.mv-row-name')?.textContent==='Analyzed Total')");const formats={};for(const style of ['original','long','short']){await run(`(()=>{const s=document.querySelector('select[aria-label="DAX layout"]');s.value=${JSON.stringify(style)};s.dispatchEvent(new Event('change',{bubbles:true}))})()`);await b.settle();formats[style]=await run("[...document.querySelectorAll('.mv-dax-body')].map(n=>n.innerText)");assert.ok(formats[style].join('').includes('DIVIDE'))}assert.notDeepEqual(formats.original,formats.long);save('measures',formats);
 await b.click("[...document.querySelectorAll('nav button')].find(n=>n.textContent==='Power Query')");await b.settle();const pq=await run('({phase:app.powerQueryWorkspace.phase,code:document.querySelectorAll(".pqi-source-line").length,nodes:document.querySelectorAll(".pqc-node").length,message:app.powerQueryWorkspace.message.textContent})');assert.equal(pq.code,0);assert.equal(pq.nodes,0);assert.match(pq.message,/unavailable/);save('pq-unavailable',pq);
 const download=path.join(out,'re-export');fs.mkdirSync(download,{recursive:true});await b.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:download,eventsEnabled:true});await b.click(button('Save snapshot'));await b.until('!app.state.snapshotSaving','re-export');assert.equal(await run('app.state.snapshotError'),'');let files=[];for(let i=0;i<100;i++){files=fs.readdirSync(download).filter(n=>n.endsWith('.html'));if(files.length)break;await new Promise(r=>setTimeout(r,50))}assert.equal(files.length,1);const exported=fs.readFileSync(path.join(download,files[0]),'utf8'),payload=JSON.parse(exported.match(/<script[^>]*id="smv-snapshot-data"[^>]*>([\s\S]*?)<\/script>/)[1]);for(const t of ['powerQuery','PQ_FLOW_PRIVATE_','queryGroup','groupPath','Curated/Outputs','Landing/SQL'])assert.ok(!JSON.stringify(payload).includes(t));assert.ok(!exported.includes('PQ_FLOW_PRIVATE_'));assert.ok(exported.includes('WorkspaceUI'));save('re-export-proof',{bytes:Buffer.byteLength(exported),sha256:crypto.createHash('sha256').update(exported).digest('hex'),payload});
 receipt.checks.push('actual downloaded snapshot opens with network offline','embedded WorkspaceUI helper available','Measures original/long/short formatting','PQ honestly unavailable without raw M','actual offline re-export remains private');fs.writeFileSync(path.join(out,'offline.png'),Buffer.from((await b.send('Page.captureScreenshot',{format:'png'})).data,'base64'));
}catch(e){receipt.failures.push(e.stack);process.exitCode=1}finally{save('network',b.events.filter(e=>/Network.requestWillBeSent|Network.loadingFailed|Runtime.exceptionThrown/.test(e.method)));save('receipt',receipt);await b.close();console.log(JSON.stringify(receipt,null,2))}})().catch(e=>{console.error(e);process.exitCode=1});
