'use strict';
// Synthetic-only supplemental browser journey after T3 explicitly reported its
// automation host unavailable. This is separate from saved T3 screenshots.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {open}=require('./pq-redesign-independent-runtime-transport.cjs');
const root=path.resolve(__dirname,'..'),out=path.join(root,'docs/verification/pq-reader-connectors-20261009'),origin='http://localhost:8945/?review=pq-reader-connectors-20261009';
const receipt={boundary:'Supplemental isolated Chrome after explicit T3 host unavailable; not native or independent acceptance',checks:[],failures:[]};
(async()=>{const b=await open(),run=b.evaluate,w='app.powerQueryWorkspace';
const button=t=>`[...document.querySelectorAll('button')].find(e=>e.textContent===${JSON.stringify(t)}&&e.getBoundingClientRect().width>0)`,row=t=>`[...document.querySelectorAll('.pqw-list .ex-table-name')].find(e=>e.querySelector('strong').textContent===${JSON.stringify(t)})`;
const check=async(name,fn)=>{await fn();receipt.checks.push({name,pass:true});fs.writeFileSync(path.join(out,'fallback-receipt.json'),JSON.stringify(receipt,null,2)+'\n');};
try{
 await b.send('Page.enable');await b.send('Runtime.enable');await b.send('Network.enable');await b.send('Emulation.setDeviceMetricsOverride',{width:1280,height:800,deviceScaleFactor:1,mobile:false});await b.send('Page.navigate',{url:origin});await b.until('!!window.app','boot');
 await b.click(button('Import model (TMDL / BIM)'));await b.until('!!document.querySelector("input[type=file][multiple]")','import input');const doc=await b.send('DOM.getDocument'),input=await b.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'input[type=file][multiple]'});await b.send('DOM.setFileInputFiles',{nodeId:input.nodeId,files:[path.join(out,'synthetic.bim')]});await b.until('app.state.importReady','parse');await b.click(`[...document.querySelectorAll('button')].find(e=>/^(Add|Update) model/.test(e.textContent))`);await b.until('!app.state.showImport','import complete');await b.click(button('Power Query'));await b.until(`${w}.phase==='ready'`,'PQ ready');
 await check('explicit BIM group intersects canvas, visible-only map and induced edge',async()=>{await run(`(()=>{const s=document.querySelector('[aria-label="Power Query group filter"]');s.value='group:Review/Inputs';s.dispatchEvent(new Event('change',{bubbles:true}));})()`);const state=await run(`({map:[...document.querySelectorAll('[data-map-id]')].map(e=>e.dataset.mapId),visible:[...${w}.visible],edges:[...document.querySelectorAll('.pqc-edge')].filter(e=>getComputedStyle(e).display!=='none').length,registry:${w}.context.graph.nodes.length})`);assert.equal(state.map.length,2);assert.deepEqual(state.map.sort(),state.visible.sort());assert.equal(state.edges,1);assert.equal(state.registry,8);await b.click(button('Reset filters'));});
 await check('membership add uses viewport, preserves previous position; Undo restores exact layout/membership',async()=>{await b.click(button('Blank layout'));await b.click(row('Sales Raw'));const before=await run(`({layout:[...${w}.canvas.captureLayout()],members:[...${w}.membership]})`);await b.click(row('Prepared Sales'));assert.equal(await run(`${w}.visible.size`),2);const positions=await run(`[...${w}.canvas.captureLayout()]`);assert.deepEqual(positions.find(([id])=>id===before.members[0]),before.layout.find(([id])=>id===before.members[0]));assert.equal(await run(`(()=>{let r=document.querySelector('.pqc-surface').getBoundingClientRect();return [...document.querySelectorAll('.pqc-node')].filter(e=>!e.hidden).every(e=>{let x=e.getBoundingClientRect();return x.left>=r.left-1&&x.right<=r.right+1&&x.top>=r.top-1&&x.bottom<=r.bottom+1});})()`),true);await b.click(button('Undo'));await b.settle();assert.deepEqual(await run(`({layout:[...${w}.canvas.captureLayout()],members:[...${w}.membership]})`),before);await b.click(button('Show all'));});
 await check('Center selected remains exact after pan/zoom; category projection remains intact',async()=>{await b.click(row('Prepared Sales'));await run(`${w}.canvas.setViewport({x:-9000,y:5000,k:.3})`);await b.click(button('Center selected'));const delta=await run(`(()=>{const w=${w},a=[...document.querySelectorAll('.pqc-node')].find(e=>e.dataset.nodeId===w.selectedId).getBoundingClientRect(),b=document.querySelector('.pqc-surface').getBoundingClientRect();return {x:a.x+a.width/2-b.x-b.width/2,y:a.y+a.height/2-b.y-b.height/2,k:w.canvas.getViewport().k};})()`);assert.ok(Math.abs(delta.x)<1&&Math.abs(delta.y)<1&&delta.k>=.85);await run(`(()=>{const s=${w}.filter;s.value='disconnected';s.dispatchEvent(new Event('change',{bubbles:true}));})()`);assert.deepEqual(await run(`[...${w}.visible].map(id=>${w}.context.byNodeId.get(id).node.label)`),['Standalone']);await b.click(button('Reset filters'));});
 await check('wide-reader exact source, scroll/disclosures/history and late completion lifecycle',async()=>{const raw=fs.readFileSync(path.join(out,'exact-source.m'),'utf8');await run(`window.expectedM=${JSON.stringify(raw)};window.codeDOM=document.querySelector('.pqi-code-scroll');document.querySelector('.pqi-provenance').open=true;document.querySelector('.pqi-analysis-details').open=true`);await b.click(button('Open full query'));assert.equal(await run(`[...document.querySelectorAll('.pqi-source-line')].map(e=>e.textContent).join('')`),raw);assert.equal(await run(`document.querySelector('.pqi-code-scroll')===codeDOM`),true);await b.click(button('Unwrap lines'));await run(`(()=>{let s=document.querySelector('.pqi-code-scroll');s.scrollLeft=150;s.scrollTop=90;document.querySelector('.pqi-reference').focus({preventScroll:true});window.savedNavigation=${w}.captureNavigation();})()`);await b.key('Enter');await b.click(button('Back'));await b.settle();assert.deepEqual(await run(`${w}.captureNavigation()`),await run('savedNavigation'));await b.key('Escape');assert.equal(await run(`document.activeElement.textContent`),'Open full query');await b.click(button('Open full query'));await run(`navigator.clipboard.writeText=()=>new Promise(r=>window.finishCopy=r)`);await b.click(button('Copy M'));await run(`${w}.inspector.suspend(true);finishCopy()`);await b.settle();assert.equal(await run(`!!document.querySelector('.pqi-reader[open]')`),false);assert.equal(await run(`document.querySelector('.pqi-copy-status').textContent`),'');await run(`${w}.inspector.suspend(false)`);});
 await check('Tables and Measures actual navigation leaves PQ manual layout intact',async()=>{await b.click(`document.querySelector('[aria-label="Close query details"]')`);const layout=await run(`[...${w}.canvas.captureLayout()]`);await b.click(button('Tables'));await b.click(button('Show all'));await b.click(button('Measures'));await b.until('!!document.querySelector(".mv-library-row")','measures');await b.click(`[...document.querySelectorAll('.mv-library-row')].find(e=>e.textContent.includes('Total Amount'))`);assert.ok((await run('document.body.innerText')).includes('SUM'));await b.click(button('Power Query'));await b.settle();assert.deepEqual(await run(`[...${w}.canvas.captureLayout()]`),layout);});
 await check('actual snapshot excludes M, PQ and groups',async()=>{const dir=path.join(out,'download');fs.mkdirSync(dir,{recursive:true});await b.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:dir,eventsEnabled:true});await b.click(button('Save snapshot'));await b.until('!app.state.snapshotSaving','snapshot');assert.equal(await run('app.state.snapshotError'),'');let files=[];for(let n=0;n<100;n++){files=fs.readdirSync(dir).filter(n=>n.endsWith('.html'));if(files.length)break;await new Promise(r=>setTimeout(r,25));}assert.equal(files.length,1);const html=fs.readFileSync(path.join(dir,files[0]),'utf8'),payload=JSON.parse(html.match(/<script[^>]*id="smv-snapshot-data"[^>]*>([\s\S]*?)<\/script>/)[1]),json=JSON.stringify(payload);for(const key of ['powerQuery','queryGroup','groupPath','Review/Inputs','Synthetic analysis column','Exact CRLF'])assert.ok(!json.includes(key),key);receipt.snapshot={sha256:crypto.createHash('sha256').update(html).digest('hex'),bytes:Buffer.byteLength(html),file:files[0]};});
 await check('queued reader restore cannot survive generation reset',async()=>{await b.click(row('Prepared Sales'));await b.click(button('Open full query'));await run(`window.lateRestore=${w}.inspector.restoreViewState({expanded:true,wrap:false,codeY:200});${w}.invalidate()`);await run('lateRestore');await b.settle();assert.equal(await run(`document.querySelectorAll('.pqi-source-line,.pqi-reader').length`),0);assert.equal(await run(`${w}.history.length+${w}.layoutHistory.length`),0);});
 receipt.runtimeExceptions=b.events.filter(e=>e.method==='Runtime.exceptionThrown');assert.equal(receipt.runtimeExceptions.length,0);
}catch(error){receipt.failures.push(error.stack);process.exitCode=1;fs.writeFileSync(path.join(out,'fallback-failure.png'),Buffer.from((await b.send('Page.captureScreenshot',{format:'png'})).data,'base64'));}
finally{fs.writeFileSync(path.join(out,'fallback-receipt.json'),JSON.stringify(receipt,null,2)+'\n');await b.close();console.log(JSON.stringify(receipt,null,2));}
})().catch(e=>{console.error(e);process.exitCode=1});
