'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{open}=require('./pq-redesign-independent-runtime-transport.cjs');
const root=path.resolve(__dirname,'..'),out=path.join(root,'docs/verification/pq-redesign/flow-0d964fc/arrange-undo-diagnostic');fs.mkdirSync(out,{recursive:true});
const R={candidate:'0d964fc97273cca8626e3cc4e9b39f73620b7e24',boundary:'T3 explicit unavailable / Do not retry; isolated Chrome targeted Arrange Undo displayed-zoom reproduction',checks:[],failures:[]};
(async()=>{const b=await open(),run=b.evaluate,save=(n,v)=>fs.writeFileSync(path.join(out,n+'.json'),JSON.stringify(v,null,2)+'\n'),button=t=>`[...document.querySelectorAll('button')].find(n=>n.textContent===${JSON.stringify(t)}&&n.getBoundingClientRect().width)`;
try{await b.send('Page.enable');await b.send('Network.enable');await b.send('Runtime.enable');await b.send('Emulation.setDeviceMetricsOverride',{width:1280,height:800,deviceScaleFactor:1,mobile:false});await b.send('Page.navigate',{url:'http://127.0.0.1:54093/'});await b.until('!!window.app&&app.state.showModelMenu','boot');await b.click(button('Import model (TMDL / BIM)'));await b.until('!!document.querySelector("input[type=file]")','fileinput');const doc=await b.send('DOM.getDocument'),input=await b.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'input[type=file]'});await b.send('DOM.setFileInputFiles',{nodeId:input.nodeId,files:[path.join(root,'tests/acceptance-fixtures/pq-redesign/flow-0d964fc/chain52.bim')]});await b.until('app.state.importReady','parsed');await b.click("[...document.querySelectorAll('button')].find(n=>/^(Add|Update) model/.test(n.textContent))");await b.click("[...document.querySelectorAll('nav button')].find(n=>n.textContent==='Power Query')");await b.until("app.powerQueryWorkspace.phase==='ready'",'ready');await b.click("[...document.querySelectorAll('.pqw-library-row')].find(n=>n.querySelector('strong').textContent==='FinalOutput')");await b.click(button('Hide unrelated'));await b.settle();
const capture=()=>run(`(()=>{const w=app.powerQueryWorkspace;return {view:w.canvas.getViewport(),label:w.zoom.textContent,layout:[...w.canvas.captureLayout()].sort((a,b)=>a[0].localeCompare(b[0])),root:w.flowRootId,selected:w.selectedId,undoDisabled:w.undoButton.disabled}})()`);
const before=await capture();await b.click(button('Arrange'));await b.settle();const arranged=await capture();await b.click(button('Undo'));await b.settle();const undone=await capture();save('observed',{before,arranged,undone});fs.writeFileSync(path.join(out,'undone.png'),Buffer.from((await b.send('Page.captureScreenshot',{format:'png'})).data,'base64'));assert.deepEqual(undone.view,before.view);assert.deepEqual(undone.layout,before.layout);assert.equal(undone.root,before.root);assert.equal(undone.label,Math.round(undone.view.k*100)+'%','Displayed zoom must reflect restored viewport after actual Arrange Undo');R.checks.push('Arrange Undo restores viewport layout and displayed zoom');
}catch(err){R.failures.push(err.stack);process.exitCode=1}finally{save('receipt',R);save('network',b.events.filter(e=>/Network.requestWillBeSent|Runtime.exceptionThrown/.test(e.method)));await b.close();console.log(JSON.stringify(R,null,2))}})().catch(e=>{console.error(e);process.exitCode=1});
