'use strict';
// True Chrome zoom and pointer resize controls not exposed by T3 preview.
// State preparation (including select-option assignment) is explicit. Selection,
// Center, reader and separator actions use trusted CDP input; native chooser is
// separately exercised with T3 preview_select, not claimed as CDP keyboard proof.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {open}=require('./pq-redesign-independent-runtime-transport.cjs');
const root=path.resolve(__dirname,'..'),out=path.join(root,'docs/verification/pq-selection-docking-r9',process.env.PQ_RUN||'zoom-docking');fs.mkdirSync(out);
const R={boundary:'T3 available; explicitly authorized true Chrome zoom and pointer resize audit; no native acceptance',checks:[],failures:[]},url='http://127.0.0.1:54093/';
(async()=>{const b=await open(),run=b.evaluate,save=(n,v)=>fs.writeFileSync(path.join(out,n+'.json'),JSON.stringify(v,null,2)+'\n');
const button=t=>`[...document.querySelectorAll('button')].find(n=>n.textContent===${JSON.stringify(t)}&&n.getBoundingClientRect().width)`;
const library=t=>`[...document.querySelectorAll('.pqw-library-row')].find(n=>n.querySelector('strong').textContent===${JSON.stringify(t)})`;
const settle=b.settle;
async function click(ex){await run(`(${ex}).scrollIntoView({block:'nearest'})`);await settle();const p=await run(`(()=>{const e=(${ex}),r=e.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2;return {x,y,own:e.contains(document.elementFromPoint(x,y))}})()`);assert(p.own,'trusted action owns hit');const prior=await capture();for(const type of ['mousePressed','mouseReleased'])await b.send('Input.dispatchMouseEvent',{type,x:p.x,y:p.y,button:'left',clickCount:1});await settle();return prior;}
const capture=()=>run(`(()=>{const w=app.powerQueryWorkspace;return {viewport:w.canvas.getViewport(),layout:[...w.canvas.captureLayout()],body:[w.body.scrollLeft,w.body.scrollTop],page:[scrollX,scrollY],root:w.flowRootId,selected:w.selectedId,below:w.below,pref:w.dockPreference,width:w.width,height:w.height,actual:w.inspectorHost.getBoundingClientRect().toJSON(),aria:{orientation:w.resizer.getAttribute('aria-orientation'),value:w.resizer.getAttribute('aria-valuenow')},code:w.inspector.captureViewState()}})()`);
const hitTitle=()=>run(`(()=>{const n=document.querySelector('.pqc-selected'),t=n.querySelector('.pqc-node-title'),r=t.getBoundingClientRect();return {rect:r.toJSON(),own:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('[data-node-id]')===n}})()`);
async function importModel(){await click(button(await run('app.state.showModelMenu')?'Import model (TMDL / BIM)':'Open model'));await b.until('!!document.querySelector("input[type=file]")','input');const d=await b.send('DOM.getDocument'),n=await b.send('DOM.querySelector',{nodeId:d.root.nodeId,selector:'input[type=file]'});await b.send('DOM.setFileInputFiles',{nodeId:n.nodeId,files:[path.join(root,'tests/acceptance-fixtures/pq-round7/model.bim')]});await b.until('app.state.importReady','parsed');await click("[...document.querySelectorAll('button')].find(n=>/^(Add|Update) model/.test(n.textContent))");await click("[...document.querySelectorAll('nav button')].find(n=>n.textContent==='Power Query')");await b.until("['ready','error'].includes(app.powerQueryWorkspace.phase)",'worker');assert.equal(await run('app.powerQueryWorkspace.phase'),'ready');}
async function dock(value){await click(button('Display'));await run(`(()=>{const s=app.powerQueryWorkspace.dockSelect;s.value=${JSON.stringify(value)};s.dispatchEvent(new Event('change',{bubbles:true}));})()`);await settle();assert.equal(await run('app.powerQueryWorkspace.dockPreference'),value);await click(button('Close display settings'));}
async function settingsZoom(value){await b.send('Page.navigate',{url:'chrome://settings/appearance'});await b.until(`(()=>{function f(r){for(const n of r.querySelectorAll('*')){if(n.id==='zoomLevel')return n;if(n.shadowRoot){const x=f(n.shadowRoot);if(x)return x}}}return !!f(document)})()`,'zoom setting');await run(`(()=>{function f(r){for(const n of r.querySelectorAll('*')){if(n.id==='zoomLevel')return n;if(n.shadowRoot){const x=f(n.shadowRoot);if(x)return x}}}const z=f(document);z.value='${value}';z.dispatchEvent(new Event('change',{bubbles:true}));})()`);await b.send('Page.navigate',{url});await b.until('!!window.app','app');await settle();}
try{await b.send('Page.enable');await b.send('Runtime.enable');await b.send('Network.enable');await b.send('Page.navigate',{url});await b.until('!!window.app','boot');const win=await b.send('Browser.getWindowForTarget');
for(const width of [1280,1440])for(const zoom of [1,2]){
 await b.send('Browser.setWindowBounds',{windowId:win.windowId,bounds:{width,height:1087}});await settingsZoom(zoom);await importModel();await run(`window.__trusted=[];document.addEventListener('pointerdown',e=>__trusted.push({trusted:e.isTrusted,target:e.target.className}),true)`);
 for(const preference of ['right','bottom']){
  const name=width+'-'+zoom+'-'+preference;console.log('CASE '+name);await click(library('Prepared'));await dock(preference);await click(button('Center selected'));
  const centered=await capture();assert((await hitTitle()).own,name+' Center own title');await click(button('Center selected'));assert.deepEqual((await capture()).viewport,centered.viewport,name+' repeatable Center');
  // Prepare an intentional pan/zoom and a legal nonzero below-body scroll.
  await run(`(()=>{const w=app.powerQueryWorkspace,v=w.canvas.getViewport();w.canvas.setViewport({x:v.x+17,y:v.y-9,k:1.13});if(w.below)w.body.scrollTop=23;})()`);await settle();const before=await capture();const dispatchBefore=await click(library('Raw West'));const selected=await capture();assert.deepEqual(selected.viewport,before.viewport,name+' ordinary library view');assert.deepEqual(selected.layout,before.layout);assert.deepEqual(selected.body,dispatchBefore.body,name+' body scroll');assert.deepEqual(selected.page,dispatchBefore.page);assert.equal(selected.root,before.root);
  await click(button('Center selected'));const cardBefore=await capture();await click("document.querySelector('.pqc-selected .pqc-node-title')");const cardAfter=await capture();assert.deepEqual(cardAfter.viewport,cardBefore.viewport,name+' ordinary card');assert.deepEqual(cardAfter.layout,cardBefore.layout);
  // Resize via actual separator keyboard and pointer, with numeric-view invariance.
  await click('app.powerQueryWorkspace.resizer');const resizeBefore=await capture();await b.key(resizeBefore.below?'ArrowUp':'ArrowLeft');await settle();const keyboard=await capture();assert.equal(keyboard.below?keyboard.height:keyboard.width,(resizeBefore.below?resizeBefore.height:resizeBefore.width)+20);assert.equal(Number(keyboard.aria.value),keyboard.below?keyboard.height:keyboard.width);assert.equal(keyboard.below?keyboard.actual.height:keyboard.actual.width,Number(keyboard.aria.value));assert.deepEqual(keyboard.viewport,resizeBefore.viewport);
  const p=await run(`(()=>{const e=app.powerQueryWorkspace.resizer,r=e.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2;return {x,y,own:e===document.elementFromPoint(x,y)}})()`);assert(p.own);await b.send('Input.dispatchMouseEvent',{type:'mousePressed',x:p.x,y:p.y,button:'left',clickCount:1});await b.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:p.x-(keyboard.below?0:15),y:p.y-(keyboard.below?15:0),button:'left',buttons:1});await b.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:p.x-(keyboard.below?0:15),y:p.y-(keyboard.below?15:0),button:'left',clickCount:1});await settle();const pointer=await capture();assert.equal(pointer.below?pointer.height:pointer.width,Number(keyboard.aria.value)+15);assert.deepEqual(pointer.viewport,keyboard.viewport);
  await click(button('Open full query'));const exact=await run(`(()=>{window.__code=document.querySelector('.pqi-code-card');const w=app.powerQueryWorkspace;return [...document.querySelectorAll('dialog .pqi-source-line')].map(n=>n.textContent).join('')===w.context.byNodeId.get(w.selectedId).code})()`);assert(exact);await b.key('Escape');await settle();assert(await run("__code===document.querySelector('.pqi-code-card')"));
  await click(button('Center selected'));assert((await hitTitle()).own);const screenshot=await b.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(screenshot.data,'base64'));
  const observed={name,zoom:await run('({innerWidth,outerWidth,dpr:devicePixelRatio,visualViewport:{width:visualViewport.width,height:visualViewport.height,scale:visualViewport.scale}})'),before,dispatchBefore,selected,keyboard,pointer,final:await capture(),hit:await hitTitle(),trusted:await run('__trusted')};save(name,observed);R.checks.push(name);
 }
}
}catch(error){R.failures.push(error.stack);process.exitCode=1;save('failure-state',await capture().catch(()=>null));fs.writeFileSync(path.join(out,'failure.png'),Buffer.from((await b.send('Page.captureScreenshot',{format:'png'})).data,'base64'));}finally{R.source=Object.fromEntries(['index.html','js/power-query-workspace.js','js/power-query-canvas.js','power-query-workspace.css'].map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'Models/tools/viewer',p))).digest('hex')]));save('receipt',R);console.log(JSON.stringify(R,null,2));await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
