'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os');
const editor=require('../vscode-extension/src/relationship-save');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'smv-rel-'));fs.mkdirSync(path.join(root,'definition','tables'),{recursive:true});for(const name of ['A','B'])fs.writeFileSync(path.join(root,'definition','tables',name+'.tmdl'),'table '+name+'\n\tcolumn Id\n');const entry={id:'model',kind:'folder',uri:{fsPath:root}},panel={};const owner={current:entry,epoch:1,isCurrent:(p,e)=>p===panel&&e===owner.epoch,modelMessage:async()=>({files:await read()})};async function read(){return fs.readdirSync(path.join(root,'definition','tables')).map(n=>({path:'definition/tables/'+n,text:fs.readFileSync(path.join(root,'definition','tables',n),'utf8')})).concat(fs.existsSync(path.join(root,'definition','relationships.tmdl'))?[{path:'definition/relationships.tmdl',text:fs.readFileSync(path.join(root,'definition','relationships.tmdl'),'utf8')}]:[]);}return{root,owner,panel,read,clean:()=>fs.rmSync(root,{recursive:true,force:true})};}
const request={modelId:'model',relationshipId:null,fromTable:'A',fromColumn:'Id',toTable:'B',toColumn:'Id',fromCardinality:'many',toCardinality:'one',crossFilteringBehavior:'oneDirection',isActive:true};
const vscode={workspace:{textDocuments:[]}};
test('review leaves source absent; save creates first file and returns refreshed metadata',async()=>{const f=fixture();try{const p=await editor.prepare(f.owner,request,f.panel,f.read);assert.equal(fs.existsSync(path.join(f.root,p.path)),false);const saved=await editor.save(f.owner,{token:p.token},f.panel,f.read,vscode);assert.equal(saved.saved,true);assert.equal(saved.model.files.length,3);await assert.rejects(()=>editor.save(f.owner,{token:p.token},f.panel,f.read,vscode),/stale/);}finally{f.clean();}});
test('endpoint schema change after review invalidates save and keeps target absent',async()=>{const f=fixture();try{const p=await editor.prepare(f.owner,request,f.panel,f.read);fs.appendFileSync(path.join(f.root,'definition/tables/A.tmdl'),'\tcolumn New\n');await assert.rejects(()=>editor.save(f.owner,{token:p.token},f.panel,f.read,vscode),/changed/);assert.equal(fs.existsSync(path.join(f.root,p.path)),false);}finally{f.clean();}});
test('concurrent first file creation and unsaved model documents invalidate save',async()=>{const f=fixture();try{const p=await editor.prepare(f.owner,request,f.panel,f.read);await assert.rejects(()=>editor.save(f.owner,{token:p.token},f.panel,f.read,{workspace:{textDocuments:[{isDirty:true,uri:{fsPath:path.join(f.root,'definition/tables/A.tmdl')}}]}}),/unsaved/);fs.writeFileSync(path.join(f.root,p.path),'// external file\n');await assert.rejects(()=>editor.save(f.owner,{token:p.token},f.panel,f.read,vscode),/changed/);assert.equal(fs.readFileSync(path.join(f.root,p.path),'utf8'),'// external file\n');}finally{f.clean();}});
